### ISSUE TITLE
Switching to tab closes tab (sometimes)

### ISSUE THREAD

**Issue by Vega-KH** [electron-utils/electron-dockable#1]
Sometimes switching to a new tab will close the currently active tab.

To reproduce the error:

1. Open the Workspace example.
2. Click on the tab titled "bar." 
3. Notice that the tab titled "alpha" closed.
4. If it did not close, click back to alpha, then bar. After a few times switching back and forth, one tab will close.

(Tested on Windows 10.)

**Comment by jwu** [comment]
hi @Vega-KH 

Sorry for the late reply, i just found i didn't watch the project so no notification send to me. I try this in the latest commit, looks like it didn't reproduced in my machine. I will try it on Windows 10 later.

Would you mind to check out to the latest version and test it again ?

**Comment by Vega-KH** [comment]
Thanks for the reply.

I have figured out the problem, and it is not what I thought.  

On Windows, none of the SVG files were loading because the calls to "__dirname" in tab.js and tabbar.js are being called from the example directory, and returning the wrong directory path.  Therefore the X (close.svg) graphic wasn't being displayed, and I was clicking it accidentally and closing the tab.

I fixed the problem with a bit of a hack.  In tab.js and tabbar.js, I made 4 changes where it loads svg:
```
OLD:
  .icon.close {
    background: url("${__dirname}/../media/close.svg") center center no-repeat;
  }

NEW:
  .icon.close {
    background: url("../../lib/renderer/media/close.svg") center center no-repeat;
  }
```
After that change, everything works fine, but using relative paths like that is problematic because it will require developers to always use the same directory structure.  I will try to think of a better solution.  Maybe using icons from font-awesome instead of svg...?

**Comment by jwu** [comment]
hi @Vega-KH 

I've fix the problem, please check my comment. Thanks for your reporting!

The reason i didn't use font-awesome is I think svg is better than font-icon. besides it will keep the module small and further more, i try to keep it simple for the ability of changing the theme freely by user.

**Comment by Vega-KH** [comment]
Great, I couldn't figure out how to fix that. Thank you for the fix and for the excellent work on this project!
